title: 'La Minimal Teatre'
email: 'info@laminimalteatre.com'
description: '' 
baseurl: "" 
url: ""
timezone: Europe/Madrid

source: './src'
destination: './build'

markdown: kramdown

# not used by plugin but by liquid template
languages: ['en', 'ca', 'es']

# Language plugin options
language_data: data.lang.%%
language_includes_dir: _i18n

collections:
  members:
    output: false
  teams:
    output: false
  shows:
    output: true

gems:
  - jekyll-language-plugin
  - octopress-debugger
