baseurl: ""
url: "/"
markdown: kramdown
source: "src"
destination: "public"


# not used by plugin but by liquid template
languages: ['en', 'es', 'ca']

collections:
  works:
    output: true

gems:
  - octopress-paginate
  - jekyll-language-plugin

language_data: data.lang.%%
language_includes_dir: _i18n

exclude:
  - node_modules
