#!/bin/sh

## Do not fetch from DatoCMS
## script/serve nofetch
if [ "$1" != "nofetch" ]
then
  echo '==> Fetching from DatoCMS'
  script/datocms
fi

echo '==> Serving the site...'
JEKYLL_ENV=development bundle exec jekyll serve --incremental $@
